### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal pattern component: XXX

### ISSUE THREAD

**Issue by henryabra** [jgperrin/net.jgp.books.spark.ch01#4]
When trying to run as described in the book (mvn) I am getting the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal pattern component: XXX
	at org.apache.commons.lang3.time.FastDateFormat.parsePattern(FastDateFormat.java:577)
	at org.apache.commons.lang3.time.FastDateFormat.init(FastDateFormat.java:444)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:437)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:110)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:109)
	at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:82)
	at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:205)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:139)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:41)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:58)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:179)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at net.jgp.books.spark.ch01.lab100_csv_to_dataframe.CsvToDataframeApp.start(CsvToDataframeApp.java:38)
	at net.jgp.books.spark.ch01.lab100_csv_to_dataframe.CsvToDataframeApp.main(CsvToDataframeApp.java:21)
```

As a fix I added `.option("timestampFormat", "MM/dd/yyyy")`. After that, the program execute as expected.
Following a patch for this change:
```
Index: src/main/java/net/jgp/books/spark/ch01/lab100_csv_to_dataframe/CsvToDataframeApp.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/net/jgp/books/spark/ch01/lab100_csv_to_dataframe/CsvToDataframeApp.java	(revision a6ef620bb47852c4dec8dea08f5f2323bfae59af)
+++ src/main/java/net/jgp/books/spark/ch01/lab100_csv_to_dataframe/CsvToDataframeApp.java	(date 1576197949011)
@@ -35,6 +35,7 @@
     // dataframe
     Dataset<Row> df = spark.read().format("csv")
         .option("header", "true")
+        .option("timestampFormat", "MM/dd/yyyy")
         .load("data/books.csv");
 
     // Shows at most 5 rows from the dataframe

```

**Comment by jgperrin** [comment]
Thanks henry! This is totallyyyyyy weird. So you had:

```
    Dataset<Row> df = spark.read().format("csv")
        .option("header", "true")
        .load("data/books.csv");
```

and you changed to:

```
    Dataset<Row> df = spark.read().format("csv")
        .option("header", "true")
        .option("timestampFormat", "MM/dd/yyyy")
        .load("data/books.csv");
```

to make it work?

Both work here. Can you share a little more anbout your environment?

**Comment by henryabra** [comment]
Sure (sorry for the delay).
OS: macOS Mojave 10.14.6
JDK: Oracle 1.8.0_144
JDK Locale: en_GB
